<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ActionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        $actions = [
            // ==================== USUÁRIOS ====================
                [
                    'controller' => 'UserController',
                    'method' => 'index',
                    'nome' => 'Listar Usuários',
                    'descricao' => 'Visualizar a lista de todos os usuários do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'UserController',
                    'method' => 'store',
                    'nome' => 'Criar Usuário',
                    'descricao' => 'Cadastrar um novo usuário no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'UserController',
                    'method' => 'update',
                    'nome' => 'Editar Usuário',
                    'descricao' => 'Atualizar informações de um usuário existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'UserController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Usuário',
                    'descricao' => 'Remover um usuário do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                [
                    'controller' => 'UserController',
                    'method' => 'salvarPermissoes',
                    'nome' => 'Gerenciar Permissões',
                    'descricao' => 'Atribuir ou remover permissões de um usuário',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // ==================== FILIAIS ====================
                [
                    'controller' => 'FilialController',
                    'method' => 'index',
                    'nome' => 'Listar Filiais',
                    'descricao' => 'Visualizar a lista de todas as filiais',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            
                [
                    'controller' => 'FilialController',
                    'method' => 'update',
                    'nome' => 'Editar Filial',
                    'descricao' => 'Atualizar informações de uma filial existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // Configurações
                [
                    'controller' => 'ConfiguracaoController',
                    'method' => 'index',
                    'nome' => 'Ver Configurações',
                    'descricao' => 'Visualizar as configurações do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                [
                    'controller' => 'ConfiguracaoController',
                    'method' => 'store',
                    'nome' => 'Criar Configurações',
                    'descricao' => 'Adicionar novas configurações ao sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                [
                    'controller' => 'ConfiguracaoController',
                    'method' => 'update',
                    'nome' => 'Editar Configurações',
                    'descricao' => 'Atualizar as configurações do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                [
                    'controller' => 'ConfiguracaoController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Configurações',
                    'descricao' => 'Remover configurações do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // Relatorios
                [
                    'controller' => 'RelatorioController',
                    'method' => 'index',
                    'nome' => 'Ver Relatórios',
                    'descricao' => 'Visualizar relatórios do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // Clientes
                [
                    'controller' => 'ClienteController',
                    'method' => 'index',
                    'nome' => 'Listar Clientes',
                    'descricao' => 'Visualizar a lista de todos os clientes',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ClienteController',
                    'method' => 'store',
                    'nome' => 'Criar Cliente',
                    'descricao' => 'Cadastrar um novo cliente no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ClienteController',
                    'method' => 'update',
                    'nome' => 'Editar Cliente',
                    'descricao' => 'Atualizar informações de um cliente existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ClienteController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Cliente',
                    'descricao' => 'Remover um cliente do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                [
                    'controller' => 'ClienteController',
                    'method' => 'detalhes',
                    'nome' => 'Ver Detalhes do Cliente',
                    'descricao' => 'Visualizar detalhes e histórico de um cliente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
        
            // Fornecedores
                [
                    'controller' => 'FornecedorController',
                    'method' => 'index',
                    'nome' => 'Listar Fornecedores',
                    'descricao' => 'Visualizar a lista de todos os fornecedores',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'FornecedorController',
                    'method' => 'store',
                    'nome' => 'Criar Fornecedor',
                    'descricao' => 'Cadastrar um novo fornecedor no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'FornecedorController',
                    'method' => 'update',
                    'nome' => 'Editar Fornecedor',
                    'descricao' => 'Atualizar informações de um fornecedor existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'FornecedorController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Fornecedor',
                    'descricao' => 'Remover um fornecedor do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            
            // Barbeiros
                [
                    'controller' => 'BarbeiroController',
                    'method' => 'index',
                    'nome' => 'Listar Barbeiros',
                    'descricao' => 'Visualizar a lista de todos os barbeiros',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'BarbeiroController',
                    'method' => 'store',
                    'nome' => 'Criar Barbeiro',
                    'descricao' => 'Cadastrar um novo barbeiro no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'BarbeiroController',
                    'method' => 'update',
                    'nome' => 'Editar Barbeiro',
                    'descricao' => 'Atualizar informações de um barbeiro existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'BarbeiroController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Barbeiro',
                    'descricao' => 'Remover um barbeiro do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

                [
                    'controller' => 'BarbeiroController',
                    'method' => 'vincularFilial',
                    'nome' => 'Vincular Filial ao Barbeiro',
                    'descricao' => 'Vincular uma filial a um barbeiro',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                
                [
                    'controller' => 'BarbeiroController',
                    'method' => 'desvincularFilial',
                    'nome' => 'Desvincular Filial do Barbeiro',
                    'descricao' => 'Remover a vinculação de uma filial de um barbeiro',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            // Categorias
                [
                    'controller' => 'CategoriaController',
                    'method' => 'index',
                    'nome' => 'Listar Categorias Produtos/Serviços',
                    'descricao' => 'Visualizar a lista de todas as categorias de serviços',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'CategoriaController',
                    'method' => 'store',
                    'nome' => 'Criar Categoria Produtos/Serviços',
                    'descricao' => 'Cadastrar uma nova categoria de serviço no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'CategoriaController',
                    'method' => 'update',
                    'nome' => 'Editar Categoria Produtos/Serviços',
                    'descricao' => 'Atualizar informações de uma categoria de serviço existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'CategoriaController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Categoria Produtos/Serviços',
                    'descricao' => 'Remover uma categoria de serviço do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // Produtos/Serviços
                [
                    'controller' => 'ProdutoController',
                    'method' => 'index',
                    'nome' => 'Listar Produtos/Serviços',
                    'descricao' => 'Visualizar a lista de todos os produtos e serviços',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ProdutoController',
                    'method' => 'store',
                    'nome' => 'Criar Produto/Serviço',
                    'descricao' => 'Cadastrar um novo produto ou serviço no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ProdutoController',
                    'method' => 'update',
                    'nome' => 'Editar Produto/Serviço',
                    'descricao' => 'Atualizar informações de um produto ou serviço existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ProdutoController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Produto/Serviço',
                    'descricao' => 'Remover um produto ou serviço do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // Categorias Financeiras
                [
                    'controller' => 'CategoriaFinanceiraController',
                    'method' => 'index',
                    'nome' => 'Listar Categorias Financeiras',
                    'descricao' => 'Visualizar a lista de todas as categorias financeiras',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'CategoriaFinanceiraController',
                    'method' => 'store',
                    'nome' => 'Criar Categoria Financeira',
                    'descricao' => 'Cadastrar uma nova categoria financeira no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'CategoriaFinanceiraController',
                    'method' => 'update',
                    'nome' => 'Editar Categoria Financeira',
                    'descricao' => 'Atualizar informações de uma categoria financeira existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'CategoriaFinanceiraController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Categoria Financeira',
                    'descricao' => 'Remover uma categoria financeira do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            // Movimentações Financeiras
                [
                    'controller' => 'MovimentacaoFinanceiraController',
                    'method' => 'index',
                    'nome' => 'Listar Movimentações Financeiras',
                    'descricao' => 'Visualizar a lista de todas as movimentações financeiras',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'MovimentacaoFinanceiraController',
                    'method' => 'store',
                    'nome' => 'Criar Movimentação Financeira',
                    'descricao' => 'Cadastrar uma nova movimentação financeira no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'MovimentacaoFinanceiraController',
                    'method' => 'update',
                    'nome' => 'Editar Movimentação Financeira',
                    'descricao' => 'Atualizar informações de uma movimentação financeira existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'MovimentacaoFinanceiraController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Movimentação Financeira',
                    'descricao' => 'Remover uma movimentação financeira do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'MovimentacaoFinanceiraController',
                    'method' => 'baixar',
                    'nome' => 'Baixar Movimentação Financeira',
                    'descricao' => 'Marcar uma movimentação financeira como paga ou recebida',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'MovimentacaoFinanceiraController',
                    'method' => 'cancelar',
                    'nome' => 'Cancelar Movimentação Financeira',
                    'descricao' => 'Cancelar uma movimentação financeira previamente baixada',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // Forma Pagamento
                [
                    'controller' => 'FormaPagamentoController',
                    'method' => 'index',
                    'nome' => 'Listar Formas de Pagamento',
                    'descricao' => 'Visualizar a lista de todas as formas de pagamento',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'FormaPagamentoController',
                    'method' => 'store',
                    'nome' => 'Criar Forma de Pagamento',
                    'descricao' => 'Cadastrar uma nova forma de pagamento no sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'FormaPagamentoController',
                    'method' => 'update',
                    'nome' => 'Editar Forma de Pagamento',
                    'descricao' => 'Atualizar informações de uma forma de pagamento existente',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'FormaPagamentoController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Forma de Pagamento',
                    'descricao' => 'Remover uma forma de pagamento do sistema',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // Comissão Barbeiro
                [
                    'controller' => 'ComissaoController',
                    'method' => 'index',
                    'nome' => 'Ver Comissões do Barbeiro',
                    'descricao' => 'Visualizar e gerenciar comissões dos barbeiros por filial e serviço',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ComissaoController',
                    'method' => 'salvarComissaoFilial',
                    'nome' => 'Salvar Comissão da Filial para Barbeiro',
                    'descricao' => 'Definir ou atualizar a comissão padrão de uma filial para um barbeiro',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ComissaoController',
                    'method' => 'salvarComissaoServico',
                    'nome' => 'Salvar Comissão de Serviço para Barbeiro',
                    'descricao' => 'Definir ou atualizar a comissão específica de um serviço para um barbeiro em uma filial',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ComissaoController',
                    'method' => 'removerComissaoServico',
                    'nome' => 'Remover Comissão de Serviço para Barbeiro',
                    'descricao' => 'Remover a comissão específica de um serviço para um barbeiro em uma filial',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

            // Produto Filial
                [
                    'controller' => 'ProdutoFilialController',
                    'method' => 'vincular',
                    'nome' => 'Vincular Produto à Filial',
                    'descricao' => 'Associar um produto a uma filial com estoque e preço específicos',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ProdutoFilialController',
                    'method' => 'atualizar',
                    'nome' => 'Atualizar Vinculação de Produto à Filial',
                    'descricao' => 'Modificar detalhes da associação de um produto a uma filial, como estoque e preço',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'ProdutoFilialController',
                    'method' => 'desvincular',
                    'nome' => 'Desvincular Produto da Filial',
                    'descricao' => 'Remover a associação de um produto a uma filial',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
            // Agendamentos
                [
                    'controller' => 'AgendamentoController',
                    'method' => 'index',
                    'nome' => 'Listar Agendamentos',
                    'descricao' => 'Visualizar a lista de todos os agendamentos',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'AgendamentoController',
                    'method' => 'store',
                    'nome' => 'Criar Slot de Agendamento',
                    'descricao' => 'Adicionar um novo slot de agendamento para um barbeiro em uma data e hora específicas',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'AgendamentoController',
                    'method' => 'associarSlot',
                    'nome' => 'Associar Slot de Agendamento a Cliente',
                    'descricao' => 'Vincular um slot de agendamento existente a um cliente',
                    'ativo' => true,
                    'created_at' => $now,   
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'AgendamentoController',
                    'method' => 'destroy',
                    'nome' => 'Excluir Agendamento',
                    'descricao' => 'Remover um agendamento do sistema',     
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'AgendamentoController',
                    'method' => 'gerarEmLote',
                    'nome' => 'Gerar Slots de Agendamento em Lote',
                    'descricao' => 'Criar múltiplos slots de agendamento para um barbeiro em um intervalo de datas e horários',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'AgendamentoController',
                    'method' => 'cancelarAtendimento',
                    'nome' => 'Cancelar Atendimento Agendado',  
                    'descricao' => 'Cancelar um atendimento previamente agendado sem excluir o slot',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'AgendamentoController',
                    'method' => 'iniciarAtendimento',
                    'nome' => 'Iniciar Atendimento Agendado',
                    'descricao' => 'Marcar o início de um atendimento agendado',
                    'ativo' => true,
                    'created_at' => $now,   
                    'updated_at' => $now,
                ],
                [
                    'controller' => 'AgendamentoController',
                    'method' => 'finalizarAtendimento',
                    'nome' => 'Finalizar Atendimento Agendado',
                    'descricao' => 'Marcar a conclusão de um atendimento agendado',
                    'ativo' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ],

        ];

        DB::table('actions')->insert($actions);
    }
}
